title: 1-Click App Deploy
captions: |
  {1}{15}Got a nice app? Deploy it!
  {17}{40}Deploying takes a short while...
  {45}{57}... almost there.
  {63}{82}Done!
  {87}{112}View the deployed app.
  {115}{178}Test the features.
  {180}{190}Looks good!
  {197}{210}Go to the app dashboard.
  {215}{232}Copy the URL and share it!
